# Generated by Django 4.2.6 on 2023-10-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_menuitem_menu_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='menu_name',
        ),
    ]
